version: '3'
services:
  app:
    build: ./backend
    volumes:
      - ./backend:/go/src
    ports:
      - "8080:8080"
    tty: true
  datastore:
    build: ./datastore
    volumes:
      - "./datastore/.data:/datastore/.data"
    environment:
      DATASTORE_PROJECT_ID: taskiwi-dev
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"
